services:
  - type: web
    name: myxploit-transports
    env: python
    plan: free
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: myxploit-db
          property: connectionString

databases:
  - name: myxploit-db
    databaseName: myxploit
    user: myxploit_user
    plan: free
